-- migrations/001.sql  First initial creation/migration
-- More info on create command: https://sqlite.org/lang_createtable.html

PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    uname TEXT NOT NULL ON CONFLICT FAIL,
    passwd TEXT NOT NULL ON CONFLICT FAIL,
    identifier TEXT NOT NULL ON CONFLICT FAIL
);
-- INSERT INTO users VALUES(1,'siru','passwd','f76895e3-3fd7-4dfc-8449-8ee7fbf24385');

CREATE TABLE IF NOT EXISTS quantityunits (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    unit TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS ingredients (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    name TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS meals (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    name TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS mealcontents (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    mealid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES meals (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ingredientid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES ingredients (id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantityvalue INTEGER NOT NULL ON CONFLICT FAIL,
    unitid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES quantityunits (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS shops (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    name TEXT NOT NULL ON CONFLICT FAIL,
    location TEXT NOT NULL ON CONFLICT FAIL,
    UNIQUE (name, location) ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS shopsbuyable (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    shopid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES shops (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ingredientid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES ingredients (id) ON DELETE CASCADE ON UPDATE CASCADE,
    price TEXT NOT NULL ON CONFLICT FAIL,
    UNIQUE (shopid, ingredientid) ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS tobuy (
    id INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
    ingredientid INTEGER NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL REFERENCES ingredients (id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantityvalue INTEGER NOT NULL ON CONFLICT FAIL,
    unitid INTEGER NOT NULL ON CONFLICT FAIL REFERENCES quantityunits (id) ON DELETE CASCADE ON UPDATE CASCADE
);

DELETE FROM sqlite_sequence;
COMMIT;
